### ISSUE TITLE
AttributeError: module 'maxflow' has no attribute 'maxflow2d'

### ISSUE THREAD

**Issue by Z-TIANQI** [HiLab-git/MIDeepSeg#3]
Hi,
Thank you for your time. When I ran the code, the UI is appeared and there is no problem setting the seed point. but when I clicked the button of segment, an error occurred:

`Traceback (most recent call last):
  File "G:\label_sys\MIDeepSeg-master\MIDeepSeg-master\mideepseg\gui.py", line 191, in on_segment
    self.graph_maker.extreme_segmentation()
  File "G:\label_sys\MIDeepSeg-master\MIDeepSeg-master\mideepseg\controler.py", line 182, in extreme_segmentation
    fix_predict = maxflow.maxflow2d(zoomed_img.astype(
AttributeError: module 'maxflow' has no attribute 'maxflow2d'`

Is there any module that can replace maxflow？Looking forward to your reply, Thank you very much!

**Comment by Z-TIANQI** [comment]
And the version of maxflow is 0.0.1. It is same as your required.

**Comment by Luoxd1996** [comment]
Hi,
I checked the code and requirements of this project. The maxflow was provided by [SimpleCRF](https://github.com/HiLab-git/SimpleCRF), you just need to install the SimpleCRF.
Best,
Xiangde.

**Comment by Z-TIANQI** [comment]
Thanks, it works!

**Comment by Luoxd1996** [comment]
You are welcome, any questions, please feel free to contact me.
Best,
Xiangde.

**Comment by GhTara** [comment]
Hello,

excuse me, unfortunately, I have some problems running this great project. I install SimpleCRF and maxflow, but I got the error when I clicked on the segment button:

>     fix_predict = maxflow.maxflow2d(zoomed_img.astype(
> AttributeError: module 'maxflow' has no attribute 'maxflow2d'
> Aborted (core dumped)

I am looking forward to your reply,
Thank you again

**Comment by mmy0921** [comment]
Hi,
Thank you for your time. When I ran the code and install the SimpleCRF， the version of maxflow is 0.0.1. It is same as your required。But it  still has errors。

Traceback (most recent call last): File "G:\label_sys\MIDeepSeg-master\MIDeepSeg-master\mideepseg\gui.py", line 191, in on_segment self.graph_maker.extreme_segmentation() File "G:\label_sys\MIDeepSeg-master\MIDeepSeg-master\mideepseg\controler.py", line 182, in extreme_segmentation fix_predict = maxflow.maxflow2d(zoomed_img.astype( AttributeError: module 'maxflow' has no attribute 'maxflow2d'

Looking forward to your reply, Thank you very much!
